### ISSUE TITLE
Shouldn't migrate deleted users

### ISSUE THREAD

**Issue by minjunyang88** [forcedotcom/scmt-server#10]
Assigned agents that are deleted shouldn't be migrated.

Don't migrate deleted users, cases with deleted users would be unassigned on the case level after migration.

**Comment by tstachl** [comment]
@minjunyang88 groups are not migrated through the server do we know deleted groups are migrated? If so should we create this issue on the app repo?

**Comment by minjunyang88** [comment]
Just checked, you are right! Deleted groups are not migrated. Only deleted users were migrated. I'll update the issue description. Thanks @tstachl !

**Comment by tstachl** [comment]
Thanks for verifying @minjunyang88!
