### ISSUE TITLE
Timestamps are not migrated correctly.

### ISSUE THREAD

**Issue by minjunyang88** [forcedotcom/scmt-server#2]
Timestamps are not migrated correctly for replies and notes for some cases.

**Comment by kpsf** [comment]
@minjunyang88 any examples or STR?

**Comment by minjunyang88** [comment]
Yea, please see more details below:
```Message timestamp on the replies is not when the message was sent in Desk, it is acutally the time of the 1st message in Desk: http://screencast.com/t/DhOUWJgg4BUP
This behavior is not consistent though, some times the time is off by hours, some times it's off by days: http://screencast.com/t/H4ptFwcL
But the first message's timestamp is always correct.

Most of the wrong timestamp is on outbound replies. ```

Does this help?

**Comment by kpsf** [comment]
Any specific cases from a test migration? I can go digging but it would be easier to have a starting point

**Comment by minjunyang88** [comment]
Yes, in the video, it has the case ID 29 in my test site.

**Comment by kpsf** [comment]
Seems we are using the created_at date, which for outbound emails means when the draft is created. This is why they are so far off. 

We should use the sent_at date instead.

**Comment by tstachl** [comment]
@kpsf do you have the line of code where we are going wrong?

**Comment by kpsf** [comment]
ye
