### ISSUE TITLE
Title and background are not migrated

### ISSUE THREAD

**Issue by minjunyang88** [forcedotcom/scmt-server#3]
Title and background are not migrated for contacts

**Comment by kpsf** [comment]
@minjunyang88 @tstachl Where were you seeing the Title not migrating properly? I can see why the background was ignored but the title seems fine.

**Comment by tstachl** [comment]
@kpsf I actually haven't seen this issue happening yet. Have you run a customer migration?

**Comment by kpsf** [comment]
Yeah the title looks fine, but we aren't creating a custom contact background field. Things on the server look fine for both title and background. I think we should move this one to the app.

**Comment by tstachl** [comment]
@kpsf based on this code snippet I found we put the background into the description field of the customer. No need to create a custom field:

https://github.com/forcedotcom/scmt-server/blob/master/src/main/java/com/salesforce/scmt/utils/DeskJsonMapUtil.java#L328

**Comment by kpsf** [comment]
Doesn't seem to be an issue. Will revisit if anyone sees problems.
