### ISSUE TITLE
Dedup custom field picklist values before creating in Salesforce

### ISSUE THREAD

**Issue by minjunyang88** [forcedotcom/scmt-server#34]
Desk allows duplicate picklist values for custom fields. But Salesforce doesn't. We should dedup the values before creating the custom fields in Salesforce.

**Comment by tstachl** [comment]
@minjunyang88 the required custom fields are built in the app part: https://github.com/forcedotcom/scmt-app/blob/master/src/classes/DeskMigrationWizardController.cls#L488-L539

**Comment by tstachl** [comment]
Issue moved to [forcedotcom/scmt-app #25](https://github.com/forcedotcom/scmt-app/issues/25) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tstachl** [comment]
The best place to tackle this is before the custom field gets created from migrating the metadata.
