### ISSUE TITLE
Grant migration user the R/W permission for the “unassigned” queue

### ISSUE THREAD

**Issue by tstachl** [forcedotcom/scmt-server#44]
@minjunyang88 commented on [Mon Mar 06 2017](https://github.com/forcedotcom/scmt-app/issues/18)

Ensure that the migration user has R/W permission for the “unassigned” queue. 

---

@tstachl commented on [Thu May 18 2017](https://github.com/forcedotcom/scmt-app/issues/18#issuecomment-302555206)

@minjunyang88 does this not happen during the "Group Member" migration?

---

@minjunyang88 commented on [Thu May 18 2017](https://github.com/forcedotcom/scmt-app/issues/18#issuecomment-302555383)

No. I had to manually assign myself to the "unassigned" queue.

**Comment by minjunyang88** [comment]
addressed by PR-45
