### ISSUE TITLE
Migration Header for all Desk api requests

### ISSUE THREAD

**Issue by kpsf** [forcedotcom/scmt-server#52]
Header would look like X-SC-MIGRATION=[site_id]

**Comment by tstachl** [comment]
@kpsf we don't have access to the `site_id` the header looks like:
`X-SCMT-Migration: devel.desk.com`

**Comment by tstachl** [comment]
Fixed in 23b94d9

**Comment by kpsf** [comment]
Can we modify to DESKCOM-SC-MIGRATION ?

Apparently using "X-" to denote custom headers is deprecated.

**Comment by tstachl** [comment]
Done cf2546a
