### ISSUE TITLE
Add XSS header

### ISSUE THREAD

**Issue by kpsf** [forcedotcom/scmt-server#58]
Ensure that the web browser's XSS filter is enabled, by setting the X-XSS-Protection HTTP response header to '1'.

Other information

The X-XSS-Protection HTTP response header allows the web server to enable or disable the web browser's XSS protection mechanism. The following values would attempt to enable it:

X-XSS-Protection: 1; mode=block

X-XSS-Protection: 1; report=http://www.example.com/xss

The following values would disable it:

X-XSS-Protection: 0

The X-XSS-Protection HTTP response header is currently supported on Internet Explorer, Chrome and Safari (WebKit).

Note that this alert is only raised if the response body could potentially contain an XSS payload (with a text-based content type, with a non-zero length).

**Comment by tstachl** [comment]
![image](https://user-images.githubusercontent.com/286093/27358739-d2e0988a-55cc-11e7-9659-482d909ad036.png)

done in 8af02d5
