### ISSUE TITLE
Migrate Article Inlined Images

### ISSUE THREAD

**Issue by kpsf** [forcedotcom/scmt-server#66]
We need to migrate inlined images and rehost them in SFDC.

1. Scan article body for desk hosted images
2. Upload these images to Salesforce, retrieve new url
3. Replace the links in the article body
4. Upload article

**Comment by tstachl** [comment]
https://resources.docs.salesforce.com/198/0/en-us/sfdc/pdf/salesforce_knowledge_import_cheatsheet.pdf
