### ISSUE TITLE
Email/reply quoted content not migrated

### ISSUE THREAD

**Issue by minjunyang88** [forcedotcom/scmt-server#7]
Quoted email content is not migrated. Need to add HtmlBody and Headers for email messages.

**Comment by kpsf** [comment]
@minjunyang88 The HTML body of an email isn't found anywhere in the API (as far as I know). I don't think this is possible without getting dev to add it into the api/v2/interactions endpoint

**Comment by minjunyang88** [comment]
@kpsf  looks like the body_html can be found if you request in the fields param on replies and message endpoints like this: https://zzz-minjunyang.desk.com/api/v2/cases/1163/replies?fields=body_html,body_text,body

But doesn't look like it's available on the interactions endpoint. So 3 options:
1- Check our code and see if we can leverage the link above. If so, what's the effort? And would it impact the tool performance?
2- Check with Dev and see if we can ask them to add this field in the interactions endpoint. If so, what's the effort and timeline?
3- If both option 1 and 2 are high, we can move this item to phase 3 since it's low priority. 

let me know if it makes sense. Thanks for looking into it!

**Comment by kpsf** [comment]
Filing a Jira ticket. In the meantime, I'll look into the LOE for #1.

**Comment by kpsf** [comment]
https://jira.desk.technology/browse/API-499

**Comment by kpsf** [comment]
Ticket has been released and I tested it out. We have to specify fields like this:

https://kprodehl.desk.com/api/v2/interactions?fields=body,body_html,body_text
