### ISSUE TITLE
Interaction Ids have exceeded the limit for 

### ISSUE THREAD

**Issue by kpsf** [forcedotcom/scmt-server#83]
I was trying to migrate the most recent cases from Support.desk.com and ran into a problem. Basically the id of the interactions is cast to a int field but the largest ID has exceeded the limit for the int type:

GET https://support.desk.com/api/v2/interactions?fields=id&since_id=2000000000
`"_embedded": {
"entries": [
{
"id": 2151931563,...`

Error: Caused by: java.lang.NumberFormatException: Expected an int but was 2170972796 at line 1 column 1910 path $._embedded.entries[0].id

**Comment by kpsf** [comment]
@tstachl Let's include this one in the current "sprint" for trial org fixes, which is due by 2/9

**Comment by kylehaver** [comment]
Importing interactions the Data Migration Wizard indicates 0 records attempted.  The Data Migration record itself (DM-014) indicated the same and the log indicated 

[2018-02-01 18:39:11]: Final Interaction Page migrated [null]
[2018-02-01 18:39:04]: Start Id: [null]. Use this if the job fails and needs to be restarted (e.g. invalid Session).

However, the Bulk job did complete and processed 1 batch successfully with 98 records and 0 Failures

**Comment by kylehaver** [comment]
The migration records for the Attachments are in a Queued state.  The oldest one is from an hour ago.  

![image](https://user-images.githubusercontent.com/15963368/35699357-a6905a2a-0744-11e8-8181-2fc8b04dfb06.png)

**Comment by kylehaver** [comment]
Also - I am not sure if this is from my attempt last night on support.desk.com but I am seeing an odd related list available on the page layout.

![image](https://user-images.githubusercontent.com/15963368/35699440-f0365292-0744-11e8-8f07-4740f6d36632.png)

**Comment by ljsfdcdev** [comment]
No errors migrating Users, groups, Accounts, Contacts, Cases, Notes, Interactions. Attachments stay Queued.

**Comment by kpsf** [comment]
Every time I migrate metadata, the permission set is cleared of the record type permissions. This is actually a big problem.
