### ISSUE TITLE
Ruby API doesn't work with /api/v2/notes

### ISSUE THREAD

**Issue by kpsf** [forcedotcom/scmt-server#88]
I'm seeing the tool get a 404 response to https://zzz-scmtkb.desk.com/api/v2/notes?page=1&per_page=100

But this loads normally in my browser. 

Turns out if you add the X-DESK-API: ruby header, then the server returns a 404 and says "Endpoint does not exist". 

Can we add this header specifically by object?

**Comment by tstachl** [comment]
This is an all or nothing approach @kpsf. When I initially added the `X-DESK-API` header only contacts didn't work, I had to add it to the default headers for the client. So we either fix notes for the ruby API or we have to continue without adding that header.

**Comment by kpsf** [comment]
We removed the ruby header.
